# Generated by Django 5.0.4 on 2024-04-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupermarketCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket_category_name', models.CharField(max_length=100)),
                ('supermarket_category_part_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'supermarket_categories',
            },
        ),
        migrations.CreateModel(
            name='Supermarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket_name', models.CharField(max_length=100)),
                ('supermarket_logo', models.CharField(max_length=100)),
                ('supermarket_base_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'supermarkets',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_image', models.CharField(max_length=100)),
                ('product_part_url', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField()),
                ('supermarket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.supermarketcategories')),
            ],
            options={
                'db_table': 'supermarket_products',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_kj', models.FloatField()),
                ('energy_kcal', models.FloatField()),
                ('fat', models.FloatField()),
                ('of_which_saturates', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('of_which_sugars', models.FloatField()),
                ('fibre', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
                ('supermarket_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.supermarketproducts')),
            ],
            options={
                'db_table': 'supermarket_product_details',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProductAllergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=100)),
                ('supermarket_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.supermarketproducts')),
            ],
            options={
                'db_table': 'supermarket_product_allergens',
            },
        ),
        migrations.AddField(
            model_name='supermarketcategories',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.supermarkets'),
        ),
    ]
