# Generated by Django 5.0.4 on 2024-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='added_at',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='supermarket_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
