# Generated by Django 5.0.4 on 2024-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_remove_shoppinglistitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
